### ISSUE TITLE
Compiler Error C2398 on BoxPacker2D.cpp

### ISSUE THREAD

**Issue by gustav21** [JamesBremner/Pack#4]
In Visual Studio 2015 I had a compiler error C2398: conversion from 'std::chrono::system_clock::rep' to 'unsigned int' requires a narrowing conversion.

This error arises in BoxPacker2D::packThem method here:

``` c++
        // randomize
        std::default_random_engine engine
        {
            std::chrono::system_clock::now().time_since_epoch().count() };
```

Changing the case of initialization from braces to parentheses has solved the problem for me:

``` c++
        // randomize
        std::default_random_engine engine
        (
            std::chrono::system_clock::now().time_since_epoch().count() );
```

About initializers and kinds of initialization one can read [here](https://msdn.microsoft.com/en-us/library/w7wd1177.aspx).

**Comment by JamesBremner** [comment]
The change you propose seems harmless.  Please fork the repository, make and test the change, and submit a pull request.  I can then accept the pull request.

**Comment by JamesBremner** [comment]
Pull request #6 accepted and merged.

Can we close this now?

**Comment by gustav21** [comment]
Sorry, sure!
