### ISSUE TITLE
Building an application that uses the packing engine

### ISSUE THREAD

**Issue by Xiong5Heng** [JamesBremner/Pack#9]
In your main.cpp file, I cannot find stdafx.h and what is cWord? whether you lose some files in the project

**Comment by JamesBremner** [comment]
Which project are you trying build?

**Comment by Xiong5Heng** [comment]
“Pack", the 3D bin packing package.

**Comment by JamesBremner** [comment]
Which **project** are you trying to build.  There are several different project in the repo.  The most important are here: https://github.com/JamesBremner/Pack/tree/master/build/codeblocks

**Comment by Xiong5Heng** [comment]
Sorry, I misunderstood what you meant before. I compiled the project in Visual Studio instead of Codeblocks, but I copied your all source codes and installed Boost. However in your main.cpp, I had some problems above: I cannot find stdafx.h header file and class cWord.

**Comment by JamesBremner** [comment]
Note this: 742a45008062c040f2ac4559892f0b8670da6ccd

**Comment by JamesBremner** [comment]
This code is not intended to be a standalone application, but to be called from other applications.  So, you should not compile https://github.com/JamesBremner/Pack/blob/master/SourceFiles/main.cpp but provide your own main.cpp and link to the source files.

**Comment by JamesBremner** [comment]
Here is a basic example of how to use the packing engine

```
#include "cPackEngine.h"

cPackEngine thePackEngine;

int main( int argc, char* argv[] )
{
    thePackEngine.Build(
        "b1:in:-1:10x10:100",
        "i1:in:7:200:1x1:1" );        // spin disallowed
    thePackEngine.Pack();

    std::cout << "Bins used: " << thePackEngine.CountBinsUsed() << "\n";

    return 0;
}
```

**Comment by JamesBremner** [comment]
I have added code for an example application that uses the packing engine, plus a codeblocks project to build it.

To make your visual studio project work with this:

 - remove main.cpp
 - add example.cpp

and everything should work nicely.  

Let me know if you have further problems.

**Comment by JamesBremner** [comment]
Hello?  Are you able to build the example application?

**Comment by JamesBremner** [comment]
All projects now build successfully.  Please confirm and close this issue.

**Comment by JamesBremner** [comment]
I have not received any communication from you in two days, so I am closing this issue.
